AWSTemplateFormatVersion: "2010-09-09"
Description: API Gateway for Cloud One Serverless Demo.
Parameters:
  # S3 Bucket Path  
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: cloudonedemo
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), dots(.) and forward slash (/).
    Default: "cloudone-serverless-demo/"
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), dots(.) and
      forward slash (/).
    Type: String

Resources:
  APIGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Body:
        swagger: '2.0'
        info:
          description: Cloud One Serverless Demo API with Amazon API Gateway.
          title: CloudOneServerlessDemoAPI
        schemes:
          - https
        paths:
          /:
            get:
              tags:
                - pets
              description: CloudOneServerlessDemo HTML web page containing API usage information
              consumes:
                - application/json
              produces:
                - text/html
              responses:
                '200':
                  description: Successful operation
                  headers:
                    Content-Type:
                      type: string
                      description: Media type of request
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: '200'
                    responseParameters:
                      method.response.header.Content-Type: '''text/html'''
                    responseTemplates:
                      text/html: |-
                        <html>
                            <head>
                              <style>
                                body {
                                    color: #333;
                                    font-family: Sans-serif;
                                    max-width: 800px;
                                    margin: auto;
                                }
                              </style>
                            </head>
                            <body>
                                <h1>Welcome to the CloudOneServerlessDemo API</h1>
                                <p>
                                    You have successfully deployed the CloudOneServerlessDemo API. You are seeing this HTML page because the <code>GET</code> method to the root resource of your API returns this content as a Mock integration.
                                </p>                               
                            </body>
                        </html>
                passthroughBehavior: when_no_match
                requestTemplates:
                  application/json: '{"statusCode": 200}'
                type: mock
      Name: CloudOneServerlessDemoAPI      
      EndpointConfiguration:
          Types: 
            - REGIONAL
      Description: Cloud One Serverless Demo API        
      Tags:
        - Key: Owner
          Value: TrendMicro
        - Key: Product
          Value: cloudone-serverless-demo
        - Key: Name
          Value: cloudone-serverless-demo