AWSTemplateFormatVersion: "2010-09-09"
Description: API Gateway for Cloud One Serverless Demo.
Parameters:
  # S3 Bucket Path  
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: cloudonedemo
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), dots(.) and forward slash (/).
    Default: "cloudone-serverless-demo/"
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), dots(.) and
      forward slash (/).
    Type: String
  C1SDStateMachineArn:
    ConstraintDescription: must be a valid AWS ARN
    Description: ARN of the State Machine that runs the Cloud One Serverless Demo workflow.
    Type: String

Resources:
  APIGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: CloudOneServerlessDemoAPI      
      Description: Cloud One Serverless Demo API
      EndpointConfiguration:
          Types: 
            - REGIONAL
      ApiKeySourceType: HEADER
      Tags:
        - Key: Owner
          Value: TrendMicro
        - Key: Product
          Value: cloudone-serverless-demo
        - Key: Name
          Value: cloudone-serverless-demo

  APIGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        ConnectionType: INTERNET
        Credentials: !GetAtt APIGatewayIAMRole.Arn
        IntegrationHttpMethod: POST
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000
        Type: AWS_PROXY
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TriggerLambdaFunction.Arn}/invocations'
      ResourceId: !GetAtt APIGatewayRestApi.RootResourceId
      RestApiId: !Ref APIGatewayRestApi

  APIGatewayIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: 'Allow'
            Principal:
              Service:
                - 'apigateway.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: LambdaAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 'lambda:*'
                Resource: !GetAtt TriggerLambdaFunction.Arn

  TriggerLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import os
          import boto3          
          def handler(event, context):
            regionName = str(os.environ.get("REGION_NAME")) if 'REGION_NAME' in os.environ else None
            stateMachineArn = str(os.environ.get("STATE_MACHINE_ARN")) if 'STATE_MACHINE_ARN' in os.environ else None
            if regionName:
              statesClient = boto3.client('stepfunctions', region_name=regionName)
              stateMachineStartExecutionResponse = statesClient.start_execution(
                stateMachineArn=stateMachineArn               
              )
              print(str(stateMachineStartExecutionResponse))              
              response = {
                'isBase64Encoded': False,
                'statusCode': 200,
                'headers': {},
                'multiValueHeaders': {},
                'body': str(stateMachineStartExecutionResponse)
              }
              return response        
      Description: AWS Lambda function to trigger the AWS State Machine workflow - C1SDStateMachine
      FunctionName: TriggerLambdaFunction-C1SDStateMachine
      Handler: index.handler
      MemorySize: 128
      Runtime: python3.8
      Environment:
        Variables:
          REGION_NAME: !Ref "AWS::Region"
          STATE_MACHINE_ARN: !Ref C1SDStateMachineArn
      Role: !GetAtt TriggerLambdaIAMRole.Arn      
      Timeout: 180

  TriggerLambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: stateMachineTriggerPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - 'states:*'
                Resource: "*"          
      Path: '/'

# Outputs
Outputs:
  APIGatewayArn:
    Value: !Ref APIGatewayRestApi
    Description: "ARN of the API Gateway created for the CloudOneServerlessDemo API"

  APIGatewayInvokeURL:
    Value: !Sub https://${APIGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/    
    Description: "REST API Endpoint of the API Gateway that can be used to trigger the SSM Run Command Invocation"